adobe/koperator

charts/kafka-operator/crds/operator-kafka-crd.yaml
charts/kafka-operator/crds/operator-kafka-topic-crd.yaml
charts/kafka-operator/crds/operator-kafka-user-crd.yaml
charts/kafka-operator/templates/_helpers.tpl
charts/kafka-operator/templates/authproxy-rbac.yaml
charts/kafka-operator/templates/crds.yaml
charts/kafka-operator/templates/operator-deployment.yaml
charts/kafka-operator/templates/operator-rbac.yaml
charts/kafka-operator/values.yaml

| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z
We needed more control on what resources are being created by the helm chart in restricted k8s environments.
We needed the following functionality:
- enable/disable rbac
- enable/disable crd's
- enable/disable service account creation
- customize service account name

Make CRDs installation and ServiceAccount name configurable

---

pkg/resources/cruisecontrol/deployment.go
pkg/resources/kafka/pod.go
pkg/util/util.go
pkg/util/util_test.go

Using Service Monitors would result in metrics duplication (since CC and Kafka pods are always scraped due to some hard coded annotations).
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | yes
| Deprecations?   | no
| Related tickets | fixes #X, partially #Y, mentioned in #Z

Remove Prometheus scraping hardcoded annotations

---

charts/kafka-operator/crds/operator-kafka-crd.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/sdk/v1beta1/kafkacluster_types.go

kubebuilder has support for documenting the fields in code and generated the crd documentation accordingly.
moved new fields descirptions and validation in code and regenerated the crds with:
`make manifests`

Add support for dedicated envoy deployment per brokerConfigGroup ADDENDUM

---

pkg/resources/envoy/configmap.go
pkg/resources/envoy/deployment.go

See https://github.com/banzaicloud/kafka-operator/issues/438
This is an internal patch on top of multi-az envoy patch.
While writing this patch I realised that this works fine for cluster "scale-up" when new brokers are added as they are automatically added in ingress as well. 
But not behaving that good for `scale-down` events when brokers are removed:
- one a broker is removed from KafkaCluster `spec` the operator does two things:
(1) triggers the broker clean decomissioning in CC (i.e. waiting for partitions to move off that broker)
(2) updates envoy config
As (1) is slower and (2) is faster there is a window of time during which the broker still has partitions but it's not reachable via ingress 
I suggest we solve the "scale-down" behaviour in a separate patch though as it's a rarer …

Reload Envoy ingress controller configuration on KafkaCluster scale up

---

pkg/resources/envoy/deployment.go

| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | none
Small changes to the envoy deployment created by the operator to add the KafkaCR labels in the template spec.
Setting labels in the KafkaCR does not transfer down to the envoy resources. As such when trying to deploy to a specific worker group bound with a label, it's not possible to pin the envoy resources at the current version.

Added KafkaCluster CR labels to the deployment template spec

---

config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/resources/envoy/configmap.go
pkg/resources/kafka/configmap.go
pkg/sdk/v1beta1/kafkacluster_types.go

| Bug fix?        | no|yes
| New feature?    | no|yes
| API breaks?     | no|yes
| Deprecations?   | no|yes
| Related tickets | fixes #X, partially #Y, mentioned in #Z

Public internal

---

charts/kafka-operator/templates/crds.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/k8sutil/status.go
pkg/resources/kafka/kafka.go
pkg/sdk/v1beta1/kafkacluster_types.go

| Bug fix?        | no
| New feature?    | yes
| API breaks?     | no
| Deprecations?   | no
| Related tickets | 
This setup is required for Kafka migration from one Kubernetes cluster to another.
For the internal protocols, we use the same (public) hostname used by the external listener.

Use external addresses for Kakfa internal listeners

---

Makefile

We made some chnages for spinnaker annotations and `preserveUnknownFields` that would be overriden by `make manifests`

make manifests should be called manually, if needed

---

.github/workflows/build-push-docker.yml
.github/workflows/build-push-kafka-docker.yml
docker/kafka/Dockerfile
docker/kafka/README.md
docker/kafka/opt/kafka/config/log4j.properties

`adobe/kafka` docker image build configuration.
A new `kafka-*` tag created in this repo triggers the image build and push to [adobe/kafka](https://hub.docker.com/r/adobe/kafka/tags?page=1&ordering=last_updated) docker hub repo.
Tags should be `kafka-<scala_version>-<kafka_version>` e.g `kafak-2.13-2.6.2`
This is based on [wurstmeister/kafka-docker](https://github.com/wurstmeister/kafka-docker) with the following additions:
1. Use `openjdk 16` in order to support container based resource monitoring
2. Use custom `log4j.properties` to get all kafka logs to stdout only

[INTERNAL] - Build apache kafka docker image using github actions

---

api/v1beta1/kafkacluster_types.go
charts/kafka-operator/templates/crds.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/resources/kafka/pod.go
pkg/util/util.go

Previously the same CruiseControl.Image field was used for both
cruise-control server image version but also kafka pod metrics reporter image
There are cases where only the cruise-control server version may require update
and avoid a kafka cluster rolling restart upgrade
Thus, allowing an optional field to set the CruiseControl.MetricsReporterImage
allows the user to specify that to control these two independently

Add an optional field in KafkaCluster resource to specify cruise control reporter image

---

api/assets/kafka/jmx-exporter.yml

| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | n/a |
PR enables Kafka JMX metrics with 3 labels, for both counters and gauges.
The current JMX Prometheus agent configuration does not support more than 2 JMX metric labels.
This results in some labels being erroneously parsed e.g.
```
kafka_network_requestmetrics_fifteenminuterate{name_ErrorsPerSec_request="ApiVersions",error="NONE",} 0.7567675751254123
```
instead of:
```
kafka_network_requestmetrics_fifteenminuterate{name="ErrorsPerSec",request="ApiVersions",error="NONE",} 0.786777163057294
```

add Kafka metric support for 3 labels

---

api/v1beta1/kafkacluster_types.go
charts/kafka-operator/templates/crds.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
controllers/tests/kafkacluster_controller_envoy_test.go
controllers/tests/kafkacluster_controller_externallistenerbindings_test.go
controllers/tests/kafkacluster_controller_test.go
docker/kafka/opt/kafka/config/log4j.properties
pkg/resources/envoy/configmap.go
pkg/resources/envoy/deployment.go
pkg/resources/envoy/service.go
pkg/resources/istioingress/gateway.go
pkg/resources/istioingress/meshgateway.go
pkg/resources/istioingress/virtualservice.go
pkg/resources/kafka/kafka.go
pkg/resources/kafka/poddisruptionbudget.go
pkg/resources/nodeportexternalaccess/service.go

| Bug fix?        | no/yes |
| New feature?    | no/yes |
| API breaks?     | no/yes |
| Deprecations?   | no/yes |
| Related tickets | fixes #X, partially #Y, mentioned in #Z |

Enable envoy tls termination

---

controllers/tests/kafkacluster_controller_envoy_test.go
pkg/resources/envoy/configmap.go

| New feature?    | yes |
Added Envoy support for HTTP/1.0 health-check requests.
The default way the LBs in Adobe Datacenters are sending health-check requests to each worker pool is via HTTP/1.0. Not having this support in Envoy results in LB health-check failures and consequently access denies.

Add Envoy support for HTTP/1.0 health-check requests

---

api/v1beta1/kafkacluster_types.go
api/v1beta1/zz_generated.deepcopy.go
charts/kafka-operator/templates/crds.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/resources/kafka/kafka.go

| Bug fix?        | no |
| New feature?    | yes |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets |  |
Added label selector for broker pods that need to be recycled during reconcile
Labeling pods for recycle can be used for rolling restarts or to offload rescheduling of the pods to the operator when nodes are tainted

Added TaintedBrokersSelector to kafkaClusterSpec

---

go.mod
go.sum

| Bug fix?        | yes? |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets |  |
As part of [#929](https://github.com/banzaicloud/koperator/pull/929), the local replacement for sub-modules was removed in favor of using valid tags. 
Adobe Koperator fork has some internal changes in the api sub-module, so we need to use the local version of the sub-module instead of the upstream version, this  forces us to revert the changes from [#929](https://github.com/banzaicloud/koperator/pull/929).

Use local replacement for sub-modules

---

api/v1alpha1/common_types.go
controllers/cruisecontroloperation_controller.go
controllers/tests/cruisecontroloperation_controller_test.go
controllers/tests/mocks/scale.go
pkg/scale/scale.go
pkg/scale/types.go

| Bug fix?        | yes |
| New feature?    | no |
| API breaks?     | no |
| Deprecations?   | no |
| Related tickets | fixes #828 |
When the request on `/state` endpoint of CC takes longer than `webserver.request.maxBlockTimeMs`,
then CC will convert the request into an async task and will respond with the `taskID` instead
of the result. 
The Koperator should handle this case by waiting for CC to complete the task.
In order to reproduce the issue, it's sufficient to set `webserver.request.maxBlockTimeMs` to a small value (e.g.: `webserver.request.maxBlockTimeMs=10`)

Handle async response from CC /state endpoint

---

api/v1beta1/kafkacluster_types.go
charts/kafka-operator/templates/crds.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
config/samples/banzaicloud_v1beta1_kafkacluster.yaml
controllers/tests/common_test.go
pkg/kafkaclient/provider.go
pkg/resources/kafka/kafka.go
pkg/resources/kafka/kafka_test.go
pkg/resources/kafka/mocks/KafkaClient.go

Cluster restarts are time consuming for big clusters.
Given that we are using Kafka `broker.rack` config to spread replicas across 3 AZs, we can speed up the cluster restart by allowing concurrent broker restarts within the same AZ. Allowing only same AZ concurrent restarts makes sure that we always have at most 1/3rd of the replicas of any topic-partition offline, not more.
- add configuration parameter `RollingUpgradeConfig.ConcurrentBrokerRestartsAllowed` which is by default 1
- allow concurrent broker restarts only if there are no failures or restarts in other AZs and if there are no more failures or restarts in the same AZ than specified by `RollingUpgradeConfig.ConcurrentBrokerRestartsAllowed` and `RollingUpgradeConfig.FailureThreshold`
- do not change the semantic of …

Allow concurrent broker restarts from same AZ (broker rack)

---

pkg/resources/kafka/kafka.go
pkg/resources/kafka/kafka_test.go

This change allows for `-` (dash) in broker rack values when building the broker to rack map used when enabling parallel broker restarts.

Allow dashes when parsing broker rack

---

main.go
pkg/util/util.go
pkg/util/util_test.go

Previously the LeaderElectionID was fixed value and in case of having multiple koperator per namespace, only one deployment would had leader elected as all deployments use the same Leases resource to vote.
Before, 4 koperator deployments, 1 lease:
```
kubectl get leases.coordination.k8s.io
NAME                                                                 HOLDER                                                                                                 AGE
controller-leader-election-helper                                    kafka-operator-7bdd0f84-918c-42d0-8c0d-d985c1618eff-67b74bhhwn2_b169f79e-220c-4689-8cee-4eb5367cb2bd   118m
```
With this Pr, 4 koperator deployments, each with its own lease:
```
kubectl get leases.coordination.k8s.io
NAME …
```

[INTERNAL] Create uniq leader ID per operator deployment

---

main.go

Currently setting the watched namespaces is done with `---namespaces`. This Pr introduces the option to also set the watched namespaces via environment variable WATCH_NAMESPACE.

[INTERNAL] Get watched namespaces from env variable

---

Dockerfile
Makefile

Cross-compile koperator for arm and intel

Cross-compile koperator for arm and intel.

---

api/v1beta1/kafkacluster_types.go
charts/kafka-operator/crds/kafkaclusters.yaml
config/base/crds/kafka.banzaicloud.io_kafkaclusters.yaml
pkg/resources/kafka/configmap.go
pkg/resources/kafka/configmap_test.go
pkg/resources/kafka/kafka.go
pkg/util/client/common.go
pkg/util/kafka/common.go
pkg/util/kafka/const.go
pkg/util/util.go
pkg/util/util_test.go

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.
This change is to allow for the kafka property `security.inter.broker.protocol` to be used by the broker pods. Currently, koperator will create the property `inter.broker.listener.name,` which is mutually exclusive with `security.inter.broker.protocol`. 
see kafka documentation on the property: https://kafka.apache.org/documentation/#brokerconfigs_security.inter.broker.protocol 
Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

Allow property security-inter-broker-protocol 

---

controllers/tests/kafkacluster_controller_envoy_test.go
controllers/tests/kafkacluster_controller_kafka_test.go
controllers/tests/kafkacluster_controller_test.go
pkg/util/util.go

This PR excludes controllers (if in KRaft mode) from external ingress .  `ShouldIncludeBroker` function is used to determine if the broker should be configured for external ingress (e.g. Envoy)

Exclude controllers from external ingress (e.g. envoy)

---

api/v1beta1/kafkacluster_types.go
api/v1beta1/kafkacluster_types_test.go
controllers/tests/kafkacluster_controller_kafka_test.go
controllers/tests/kafkacluster_controller_test.go
pkg/resources/kafka/configmap.go
pkg/resources/kafka/configmap_test.go
pkg/resources/kafka/kafka.go
pkg/resources/kafka/pod.go
pkg/util/kafka/const.go

To support zk to kraft migration:
- enhancement to configure CLUSTER_ID
- enable brokers to use ZK or kraft for metadata by using `migration.broker.kRaftMode` property in the readOnlyConfig
- enable brokers to add/remove the controller quorum (`controller.quorum.voters`/`controller.listener.names`) by using `migration.broker.controllerQuorumConfigEnabled`

Zk kraft migration

---

pkg/resources/kafka/configmap.go
pkg/resources/kafka/configmap_test.go

Please provide a meaningful description of what this change will do, or is for. Bonus points for including links to
related issues, other PRs, or technical references.
Note that by _not_ including a description, you are asking reviewers to do extra work to understand the context of this
change, which may lead to your PR taking much longer to review, or result in it not being reviewed at all.

adding fix for koperator to add interBrokerListenerName one at a time and check for security.inter.broker.protocol
